### ISSUE TITLE
문자열 순회 방법 성능은?

### ISSUE THREAD

**Issue by OHHAKO** [TheCopiens/algorithm-study#47]
charAt vs char 배열만들어 순회하기 둘 중 어떤 방법이 더 빠를까?

만개, 1억개의 데이터를 기준으로 어떤 방법이 더 빠를지 비교해보기로 한다.

**Comment by sypark9646** [comment]
@OHHAKO 

String 길이 천만개로 했을 때,
charAt: 86208ms
char Array: 74381ms 으로 char Array가 조금 더 빠르긴 한데,

백만개로 하면 charAt이 더 빠릅니다
charAt: 1542ms
char Array: 1836ms

**Comment by OHHAKO** [comment]
String길이 천만개부터는 toCharArray로 배열을 만들어 순회하는게 더 빠르군요!
